# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## The name and namespace are passed by helm command line parameters, use following options only if you want to override cli parameters.

## Containers ################################################

containers:
  default:
    name: app
    enabled: true

## Services ##################################################

services:
  svc1:
    name: service
    enabled: true
    type: ClusterIP
    port: 80
    protocol: TCP

## Ingress ##################################################

ingress:
  enabled: false

## Health Checks ##################################################

readinessProbe:
  failureThreshold: 3
  periodSeconds: 10
  successThreshold: 1
  tcpSocket:
    port: 80
  timeoutSeconds: 1

startupProbe:
  failureThreshold: 12
  periodSeconds: 5
  successThreshold: 1
  tcpSocket:
    port: 80
  timeoutSeconds: 1

## Persistent Volume Claims ########################################

pvcs:
  pvc1:
    name: data
    enabled: true
    storageClass: longhorn
    accessModes:
      - ReadWriteOnce
    size: 200Mi
    annotations: {}
    selector: {}
    dataSource: {}
    existingClaim: ""

## Other ##########################################################

affinity:
  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - ${K_NAME}
        topologyKey: kubernetes.io/hostname
  podAntiAffinity: {}
