# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## The name and namespace are passed by helm command line parameters, use following options only if you want to override cli parameters.

## Persistent Volume Claims ########################################

pvcs:
  pvc1:
    name: data
    enabled: true
    storageClass: longhorn
    accessModes:
      - ReadWriteOnce
    size: 200Mi
    annotations: {}
    selector: {}
    dataSource: {}
    existingClaim: ""
